census:
  version:
    "2023-12-15"
  organism: 
    "homo_sapiens"
embeddings:
  census:
    [scvi, geneformer]
metrics:
  tissues:
    ["adipose tissue", "spinal cord"]
  bio: 
    ["leiden_nmi", "leiden_ari", "silhouette_label"]
  batch: 
    ["silhouette_batch", "ilisi_knn_batch"]

