census:
  organism: 
    "homo_sapiens"
  obs_query: # Use if you want to train on a subset of the model
    null
  obs_query_model: # Required when loading data for model training. Do not change.
    'is_primary_data == True and nnz >= 300'
hvg:
  top_n_hvg: 
    8000
  hvg_batch: 
    [suspension_type, assay]
anndata:
  batch_key:
    [dataset_id, assay, suspension_type, donor_id]
  model_filename:
    anndata_model.h5ad
model:    
  filename: "scvi.model"
  n_hidden: 512
  n_latent: 50
  n_layers: 1
train:
  max_epochs: 100
  batch_size: 1024
  train_size: 0.9
  early_stopping: False
  multi_gpu: False
  num_workers: 4
  devices: [0, 1, 2, 3]
training_plan:
  lr: 1.0e-4
  n_epochs_kl_warmup: 20
  max_kl_weight: 1