census:
  organism: 
    "mus_musculus"
  obs_query:
    'tissue_general == "heart" and is_primary_data == True and nnz >= 300'
hvg:
  top_n_hvg: 
    8000
  hvg_batch: 
    [suspension_type, assay]
model:
  n_hidden: 512
  n_latent: 200
  n_layers: 1
  dropout_rate: 0.1
train:
  max_epochs: 20
  batch_size: 1048
  train_size: 0.95
  early_stopping: True
  trainer:
    early_stopping_patience: 2
    early_stopping_monitor: elbo_train # should be validation_loss - see https://github.com/chanzuckerberg/cellxgene-census/issues/777#issuecomment-1743196837
    check_val_every_n_epoch: 1
  num_workers: 4
  devices: [0, 1, 2, 3]
training_plan:
  lr: 1.0e-4