census:
  organism: 
    "mus_musculus"
  obs_query:
    'tissue_general == "heart" and is_primary_data == True'
hvg:
  top_n_hvg: 
    8000
  hvg_batch: 
    dataset_id
  min_genes:
    300
model:
  n_hidden: 512
  n_latent: 200
  n_layers: 1
  dropout_rate: 0.1
train:
  max_epochs: 20
  batch_size: 1048
  train_size: 0.95
  early_stopping: True
  trainer:
    early_stopping_patience: 2
    early_stopping_monitor: validation_loss
    check_val_every_n_epoch: 1
  num_workers: 4
  devices: [0, 1, 2, 3]
training_plan:
  lr: 1e-4