version 0.2

phases:
  pre_build:
    commands:
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 699936264352.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
    - IMAGE_TAG=699936264352.dkr.ecr.us-west-2.amazonaws.com/omics:census-geneformer
    - docker build --build-arg CELLXGENE_CENSUS_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION -t $IMAGE_TAG .
  post_build:
    commands:
    - docker push $IMAGE_TAG
