name: Close inactive pull requests
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: [self-hosted, Linux, X64]
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          days-before-issue-stale: -1 # Do not mark any issues as stale
          days-before-pr-stale: 28
          days-before-pr-close: 3
          stale-pr-message: "This PR has not seen any activity in the past 4 weeks; if no one comments or reviews it in the next 3 days, this PR will be closed."
          close-pr-message: "This PR was closed because it has been inactive for 31 days, 3 days since being marked as stale. Please re-open if you still need this to be addressed."
          stale-pr-label: "stale"
          close-pr-label: "autoclosed"
          exempt-draft-pr: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
