name: Census LTS Compatibility  # Compat test between Census package and LTS builds

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: # used for debugging or manual validation
  
jobs:
  python-compat-check:
    name: Python LTS compatibility check

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        census-build-version:  # Add additional LTS releases as they occur
          - "latest"
          - "stable"
          - "2023-12-15"
          - "2023-07-25"
          - "2023-05-15"
        py-pkg-version:
          - "~=1.10.0"
          - "~=1.11.0"
          - "~=1.12.0"
          - "~=1.13.0"
          - "head-of-main"

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          GIT_CLONE_PROTECTION_ACTIVE=false pip install -r ./api/python/cellxgene_census/scripts/requirements-dev.txt

          if [ {{matrix.py-pkg-version}} = "head-of-main" ]; then
            pip install -e ./api/python/cellxgene_census/
          else
            pip install -U cellxgene_census${{ matrix.py-pkg-version }}
          fi

      - name: Test with pytest (API, main tests)
        run: |
          PYTHONPATH=. pytest -v -rP -m lts_compat_check ./api/python/cellxgene_census/tests/test_lts_compat.py --census_version ${{ matrix.census-build-version }}
