name: Compat test between Census package and LTS builds

on:
  pull_request:  # TODO: remove befor landing
  # schedule:
  #   - cron: "30 1 * * *"
  # workflow_dispatch: # used for debugging or manual validation
  
jobs:
  python-compat-check:
    name: Python LTS compatibility check

    strategy:
      matrix:
        os: [ubuntu-latest]  # [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
        census-version: [latest]  # ["latest", "stable", "2023-07-25", "2023-05-15"]
        cellxgene-census-version: ["~=1.6.0", "head-of-main"]  # ["==1.0.0", "~=1.0.0", "~=1.1.0", "~=1.2.0", "~=1.3.0", "~=1.4.0", "~=1.5.0", "~=1.6.0", "head-of-main"]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (including experimental)
        run: |
          python -m pip install -U pip setuptools wheel pytest
          # pip install -r ./api/python/cellxgene_census/scripts/requirements-dev.txt

          if [ {{matrix.cellxgene-census-version}} != "head-of-main" ]; then
            pip install -e './api/python/cellxgene_census/'
          else
            pip install -U cellxgene_census=={{matrix.cellxgene-census-version}}
          fi

      - name: Test with pytest (API, main tests)
        run: |
          PYTHONPATH=. pytest -v -rP -m lts_compat_check ./api/python/cellxgene_census/tests/ --census_version {{matrix.census-version}}
